// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF-moVh39uUwLY9bjZU8PMLmlXeEtqlKA',
    appId: '1:1069740129570:web:0e186244a20942fef5397b',
    messagingSenderId: '1069740129570',
    projectId: 'note-app-19b86',
    authDomain: 'note-app-19b86.firebaseapp.com',
    storageBucket: 'note-app-19b86.firebasestorage.app',
    measurementId: 'G-YLDZC28WYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFZwa5hnMuVQrv4KPyaXIYjl5wvJ-iQQI',
    appId: '1:1069740129570:android:48585d79a50ece46f5397b',
    messagingSenderId: '1069740129570',
    projectId: 'note-app-19b86',
    storageBucket: 'note-app-19b86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDreLW1_Ytg_PKW-LACf9WuJRbpdkBJbt0',
    appId: '1:1069740129570:ios:31364260dfdb762ef5397b',
    messagingSenderId: '1069740129570',
    projectId: 'note-app-19b86',
    storageBucket: 'note-app-19b86.firebasestorage.app',
    iosClientId: '1069740129570-dtnbi5l4qhch8l68bevmif51ameceo1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDreLW1_Ytg_PKW-LACf9WuJRbpdkBJbt0',
    appId: '1:1069740129570:ios:31364260dfdb762ef5397b',
    messagingSenderId: '1069740129570',
    projectId: 'note-app-19b86',
    storageBucket: 'note-app-19b86.firebasestorage.app',
    iosClientId: '1069740129570-dtnbi5l4qhch8l68bevmif51ameceo1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF-moVh39uUwLY9bjZU8PMLmlXeEtqlKA',
    appId: '1:1069740129570:web:ed119f2a388566daf5397b',
    messagingSenderId: '1069740129570',
    projectId: 'note-app-19b86',
    authDomain: 'note-app-19b86.firebaseapp.com',
    storageBucket: 'note-app-19b86.firebasestorage.app',
    measurementId: 'G-D62BEZE8SM',
  );

}